# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170831_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contenu',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='comment',
            name='nom',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='titre',
            field=models.CharField(max_length=250),
        ),
    ]
