# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('modifier_le', models.DateTimeField(auto_now=True)),
                ('ajouter_le', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('detail', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-ajouter_le', '-modifier_le'),
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('texte', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='temoignages/%Y/%m/%d')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-cree_le',),
            },
        ),
    ]
