# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_auto_20170831_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='ajouter_le',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='modifier_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='titre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='nom',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='texte',
            field=models.TextField(),
        ),
    ]
